name: page_analyzer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry 
      - run: make install
      - run: poetry add --group=dev flake8